# See https://docs.github.com/graphql/reference/objects#repository for the
# GraphQL names of repo settings and https://docs.github.com/rest/reference/repos#update-a-repository
# for the REST names of repo settings.

skipForks: true
orgs: [sbsev] # list of org logins whose repos should be configured
settings:
  deleteBranchOnMerge:
    restName: delete_branch_on_merge
    value: true
  mergeCommitAllowed:
    restName: allow_merge_commit
    value: false
  hasWikiEnabled:
    restName: has_wiki
    value: false
