# See https://docs.github.com/graphql/reference/objects#repository for the GraphQL names
# of repo settings and https://docs.github.com/rest/repos/repos
# for the REST names of repo settings.

skipForks: true
orgs: [sbsev] # list of org logins whose repos should be configured
settings:
  deleteBranchOnMerge:
    restName: delete_branch_on_merge
    value: true
  mergeCommitAllowed:
    restName: allow_merge_commit
    value: false
  autoMergeAllowed:
    restName: allow_auto_merge
    value: true
  hasWikiEnabled:
    restName: has_wiki
    value: false
