name: Set all repo configs

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 10 * * 0' # 10:00 UTC every Sunday

jobs:
  config:
    name: Configure repos
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install '.[test]'

      - name: Run tests
        run: pytest

      - name: Run auto-repo-config
        run: python auto_repo_config.py
