name: Auto Repo Config

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['**/*.py', '.repo-config.yaml'] # only run workflow when source or config files changed
  schedule:
    - cron: '0 10 * * 0' # 10:00 UTC every Sunday

jobs:
  config:
    name: Configure repos
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          cache: pip
          cache-dependency-path: setup.cfg

      - name: Install dependencies
        run: pip install .

      - name: Run auto-repo-config
        run: python auto_repo_config.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
