name: Auto Repo Config

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['**.py', '.repo-config.yaml'] # only run workflow when source or config files changed
  schedule:
    - cron: '0 10 * * 0' # at 10:00 UTC every Sunday (https://crontab.guru)

jobs:
  config:
    name: Configure Repos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install Dependencies
      run: pip install pyyaml requests

    - name: Run auto_repo_config.py
      run: python auto_repo_config.py
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
