name: Auto Repo Config

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['**/*.py', '.repo-config.yaml'] # only run workflow when source or config files changed
  schedule:
    - cron: '0 10 * * 0' # 10:00 UTC every Sunday

jobs:
  config:
    name: Configure repos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: pip install .

    - name: Run auto-repo-config
      run: python auto_repo_config.py
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
